Disable FORTIFY on MUSL as there is a bug in std::to_string() in gcc
I feel stupid when I say so, but the error is:
```
alpine-release > /usr/include/fortify/stdio.h: In function '__to_xstring.constprop':
alpine-release > /usr/include/fortify/stdio.h:73:28: error: inlining failed in call to 'always_inline' 'vsnprintf': function body can be overwritten at link time
alpine-release >    73 | _FORTIFY_FN(vsnprintf) int vsnprintf(char * _FORTIFY_POS0 __s, size_t __n,
alpine-release >       |                            ^
alpine-release > /usr/include/c++/14.2.0/ext/string_conversions.h:113:32: note: called from here
alpine-release >   113 |       const int __len = __convf(__s, __n, __fmt, __args);
alpine-release >       |                                ^
```

File /usr/include/c++/14.2.0/ext/string_conversions.h:113:32 is within
such a call (maybe not this overload of to_string(), not sure):
```
  inline __vstring
    to_string(long __val)
      { return __gnu_cxx::__to_xstring<__vstring>(&std::vsnprintf, 4 * sizeof(long), "%ld", __val); }
```

so it really seems that at least one overload of to_string() is
calling vsnprintf in a way that makes its body to change, breaking
things when fortify is used, which is the case on Alpine/MUSL.

I fail to reproduce this on non-MUSL systems (tested on my box only :)