Add a fast hash function (mandates C++14 for MC)
This comes from
https://github.com/RedSpah/xxhash_cpp/commit/a310676e1514b49d78f0c9ced0678efea4f82fd9

This requires C++14:
  xxhash.hpp:288:40: error: variable declaration in a constexpr function is a C++14 extension

So bump the dependencies of the Model Checker to C++14. That's an
intrusive move, but MC is experimental anyway, and C++14 isn't that
modern anymore.