Use memcpy instead of strncpy.
Fix build error with gcc 8.1:
error: 'strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]