Fix build error: implicit declaration of function 'getline'.
On Debian/Lenny, #include "simgrid_config.h" needs to be the first include
for getline to be found.

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/simgrid/simgrid/trunk@9677 48e7efb5-ca39-0410-a469-dd3cf9ba447f