Revert "Please mingw."
This reverts commit f364225c23f541330fdc9a512d551a683cf374c9.

It was supposed to fix warnings, but now gives errors:

C:/projects/simgrid/include/simgrid/s4u/Mailbox.hpp:116:26: error: function 'void simgrid::s4u::intrusive_ptr_add_ref(simgrid::s4u::Mailbox*)' definition is marked dllimport
   friend XBT_PUBLIC void intrusive_ptr_add_ref(Mailbox*) {}
                          ^
C:/projects/simgrid/include/simgrid/s4u/Mailbox.hpp:116:26: warning: 'void simgrid::s4u::intrusive_ptr_add_ref(simgrid::s4u::Mailbox*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
C:/projects/simgrid/include/simgrid/s4u/Mailbox.hpp:116:26: error: function 'void simgrid::s4u::intrusive_ptr_add_ref(simgrid::s4u::Mailbox*)' definition is marked dllimport